# Generated by Django 3.0.6 on 2020-05-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200519_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
