# Generated by Django 3.0.6 on 2020-05-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_registration', '0003_auto_20200519_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='uuid',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='uuid',
            new_name='transaction_id',
        ),
    ]
