# Generated by Django 3.0.6 on 2020-05-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_transfer', '0003_details_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='uuid',
            new_name='transaction_id',
        ),
    ]
